common:
  includes:
  - Drivers
  - Drivers\CMSIS
  - Drivers\CMSIS\Device
  - Drivers\CMSIS\Device\ST
  - Drivers\CMSIS\Device\ST\STM32F1xx
  - Drivers\CMSIS\Device\ST\STM32F1xx\Include
  - Drivers\CMSIS\Include
  - Drivers\STM32F1xx_HAL_Driver
  - Drivers\STM32F1xx_HAL_Driver\Inc
  - Drivers\STM32F1xx_HAL_Driver\Inc\Legacy
  - Inc
  - Middlewares
  - Middlewares\ST
  - Middlewares\ST\STM32_USB_Device_Library
  - Middlewares\ST\STM32_USB_Device_Library\Class
  - Middlewares\ST\STM32_USB_Device_Library\Class\CDC
  - Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Inc
  - Middlewares\ST\STM32_USB_Device_Library\Core
  - Middlewares\ST\STM32_USB_Device_Library\Core\Inc
  sources:
    Drivers:
    - Drivers\STM32F1xx_HAL_Driver\Src
    IDE:
    - IDE\IAR
    Middlewares:
    - Middlewares\ST\STM32_USB_Device_Library\Class\CDC\Src
    - Middlewares\ST\STM32_USB_Device_Library\Core\Src
    Src:
    - Src
  target:
  - stm32f103c8
tool_specific:
  iar_arm:
    linker_file:
    - IDE\IAR\stm32f103xb_flash.icf
